//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFocus.VRIS.Web.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentAttendee
    {
        public int AppointmentAttendeeId { get; set; }
        public string AppointmentId { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public bool IsOrganizer { get; set; }
        public bool IsRequired { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
