//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFocus.VRIS.Web.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.AppointmentAttendees = new HashSet<AppointmentAttendee>();
        }
    
        public string AppointmentId { get; set; }
        public string Subject { get; set; }
        public string Room { get; set; }
        public System.DateTime StartUtc { get; set; }
        public System.DateTime EndUtc { get; set; }
        public bool IsAllDay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentAttendee> AppointmentAttendees { get; set; }
    }
}
